#!/usr/bin/env python3
"""Writes docs/LAYOUT_REFERENCE.md from tools/kbdusx.xml."""
import os
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "docs/LAYOUT_REFERENCE.md")

ORDER = (["VK_OEM_3"] + ["VK_%d" % d for d in list(range(1, 10)) + [0]]
         + ["VK_OEM_MINUS", "VK_OEM_PLUS"]
         + ["VK_" + c for c in "QWERTYUIOP"] + ["VK_OEM_4", "VK_OEM_6", "VK_OEM_5"]
         + ["VK_" + c for c in "ASDFGHJKL"] + ["VK_OEM_1", "VK_OEM_7"]
         + ["VK_" + c for c in "ZXCVBNM"]
         + ["VK_OEM_COMMA", "VK_OEM_PERIOD", "VK_OEM_2"])
LABEL = {"VK_OEM_3": "`", "VK_OEM_MINUS": "-", "VK_OEM_PLUS": "=", "VK_OEM_4": "[",
         "VK_OEM_6": "]", "VK_OEM_5": "\\", "VK_OEM_1": ";", "VK_OEM_7": "'",
         "VK_OEM_COMMA": ",", "VK_OEM_PERIOD": ".", "VK_OEM_2": "/"}
DEAD_LABEL = {"ACUTE/CEDILLA": "acute", "UMLAUT": "diaeresis", "GRAVE": "grave",
              "TILDE": "tilde", "CIRCUMFLEX": "circumflex"}
LEVELS = [("Base", ""), ("Shift", "VK_SHIFT"),
          ("AltGr", "VK_CONTROL VK_MENU"), ("Shift+AltGr", "VK_SHIFT VK_CONTROL VK_MENU")]


def text_of(res):
    t = res.get("Text")
    if t is not None:
        return t
    cps = res.get("TextCodepoints")
    return "".join(chr(int(c, 16)) for c in cps.split()) if cps else None


def code(s):
    """A markdown code span that survives backticks and pipes inside a table."""
    if s == "`":
        return "<code>&#96;</code>"
    if s == "|":
        return "<code>&#124;</code>"
    return "`%s`" % s


def cell(s):
    if s is None:
        return "&nbsp;"
    if s == " ":
        return "space"
    return code(s) + (" U+%04X" % ord(s) if len(s) == 1 and ord(s) > 127 else "")


def main():
    root = ET.parse(os.path.join(HERE, "kbdusx.xml")).getroot()
    pks = {pk.get("VK"): pk for pk in root.find("PhysicalKeys")}
    dead_tables = {}

    L = []
    w = L.append
    w("# US-International, the complete layout")
    w("")
    w("Generated by `tools/gen_reference_doc.py` from `tools/kbdusx.xml`, a")
    w("disassembly of the `KBDUSX.DLL` that ships with Windows, published at")
    w("<https://kbdlayout.info/kbdusx/>. This is the specification the Kotlin tables")
    w("in `UsIntlTables.kt` are generated from, written out in a form a person can")
    w("read and check against a real Windows machine.")
    w("")
    w("Empty cells are positions the layout does not define. Those keys type nothing")
    w("at that level, and this IME passes them through untouched.")
    w("")
    w("## Key positions")
    w("")
    w("| Key | Base | Shift | AltGr | Shift+AltGr |")
    w("| --- | --- | --- | --- | --- |")
    for vk in ORDER:
        pk = pks.get(vk)
        if pk is None:
            continue
        by_with = {(r.get("With") or ""): r for r in pk.findall("Result")}
        label = LABEL.get(vk, vk.replace("VK_", ""))
        cells = []
        for _, with_attr in LEVELS:
            res = by_with.get(with_attr)
            if res is None:
                cells.append("&nbsp;")
                continue
            dkt = res.find("DeadKeyTable")
            if dkt is not None:
                name = DEAD_LABEL[dkt.get("Name")]
                lit = next(e.get("Text") for e in dkt.findall("Result") if e.get("With") == " ")
                cells.append("**dead %s** (%s)" % (name, code(lit)))
                dead_tables[name] = dkt
                continue
            cells.append(cell(text_of(res)))
        w("| %s | %s |" % (code(label), " | ".join(cells)))
    w("")
    w("## Dead key compositions")
    w("")
    for name in ["acute", "grave", "tilde", "circumflex", "diaeresis"]:
        dkt = dead_tables[name]
        lit = next(e.get("Text") for e in dkt.findall("Result") if e.get("With") == " ")
        pairs = []
        for e in dkt.findall("Result"):
            base, out = e.get("With"), text_of(e)
            if base is None or out is None or base == " ":
                continue
            pairs.append("%s %s" % (code(base), out))
        w("**%s** (%s), %d compositions plus space:" % (name, code(lit), len(pairs)))
        w("")
        w("> " + ", ".join(pairs))
        w("")
        w("> `space` gives %s" % code(lit))
        w("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
